name: Upload Upstream Tags To Stable
on:
  push:
    tags: '*'  # All tag releases

jobs:
  build:
    name: Create package for upstream
    runs-on:
      - ubuntu-latest
    steps:
    - name: Checking out repo
      uses: actions/checkout@v2
    - name: Install snapcraft
      run: sudo snap install snapcraft --classic
    - name: Logging into snapstore
      run: echo "${{ secrets.SNAPSTORE_TOKEN }}" | sudo snapcraft login --with -
    - name: Build snap across archs
      run: snapcraft remote-build --launchpad-accept-public-upload
    - name: Pushing to snaptore
      run: for arch in arm64 armhf amd64 i386; do sudo snapcraft push ./youtube-dl_*_${arch}.snap --release=stable; done 
